version: '3.7'
services:
  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./sites-available:/etc/nginx/sites-available
      - ./sites-enabled:/etc/nginx/sites-enabled
      - ./live:/etc/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app_network
  backend:
    build:
      context: ../../backend/
      dockerfile: Dockerfile
    image: hackyeah2024_backend:latest
    ports:
      - "8080:8080"
    depends_on:
      - nginx
    env_file:
      - ../../.env
    networks:
      - app_network
  frontend:
    build:
      context: ../../frontend/
      dockerfile: Dockerfile
    image: hackyeah2024_frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - nginx
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
